export interface Token {
  id: string
  name: string
  symbol: string
  mintAddress: string
  marketCap: number | null
  price: number | null
  launchDate: string
  hasLiquidity: boolean
  verified: boolean
  trending: boolean
  logoUrl?: string
}

export const tokens: Token[] = [
  {
    id: "1",
    name: "SynthFi",
    symbol: "SYNTH",
    mintAddress: "D9mendaps8MaMHtLz2w8Duum3FfamPh2yWX5owKZpump",
    marketCap: 2500000,
    price: 0.025,
    launchDate: "2023-12-01",
    hasLiquidity: true,
    verified: true,
    trending: true,
    logoUrl: "/abstract-sf.png",
  },
  {
    id: "2",
    name: "Staking Token",
    symbol: "STAKE",
    mintAddress: "8HGyAAB1yoM1TTCznfic8vqXgdLZRwPELJfhLuUUKYed",
    marketCap: 1200000,
    price: 0.012,
    launchDate: "2023-12-15",
    hasLiquidity: true,
    verified: true,
    trending: false,
    logoUrl: "/stylized-letter-st.png",
  },
  {
    id: "3",
    name: "Vesting Protocol",
    symbol: "VEST",
    mintAddress: "7VHUFJHWu2CuExkJcJrzhQPJ9Sy2R4YBjPALfUJcjvxr",
    marketCap: 800000,
    price: 0.008,
    launchDate: "2024-01-05",
    hasLiquidity: true,
    verified: false,
    trending: false,
    logoUrl: "/abstract-vp.png",
  },
  {
    id: "4",
    name: "Airdrop Finance",
    symbol: "AIRD",
    mintAddress: "3XTkPgvp4QQQBKkKGKnJxJQfWKuZJbRQUt9D9PFTsNKm",
    marketCap: 350000,
    price: 0.0035,
    launchDate: "2024-01-20",
    hasLiquidity: true,
    verified: false,
    trending: true,
    logoUrl: "/abstract-geometric-AF.png",
  },
  {
    id: "5",
    name: "Governance DAO",
    symbol: "GOV",
    mintAddress: "6YR1MrGCLHCDPHS5VJc3GLc4UPYfZQmUzXkJqt7zMwvh",
    marketCap: 1800000,
    price: 0.018,
    launchDate: "2023-11-10",
    hasLiquidity: true,
    verified: true,
    trending: false,
    logoUrl: "/abstract-geometric-design.png",
  },
  {
    id: "6",
    name: "Yield Farming",
    symbol: "YIELD",
    mintAddress: "9XzGnaBL4GzHfZ5bQrVDrAA5q5PFuBr9YhJvmrKtXVxE",
    marketCap: 650000,
    price: 0.0065,
    launchDate: "2024-02-01",
    hasLiquidity: true,
    verified: false,
    trending: true,
    logoUrl: "/stylized-yf.png",
  },
  {
    id: "7",
    name: "NFT Marketplace",
    symbol: "NFTM",
    mintAddress: "2ZjLCp9RxPk4KfmPXQUZj9GyAEgWLkr3hhT8vzK6LGqZ",
    marketCap: 920000,
    price: 0.0092,
    launchDate: "2024-02-15",
    hasLiquidity: true,
    verified: false,
    trending: false,
    logoUrl: "/abstract-geometric-nm.png",
  },
  {
    id: "8",
    name: "Lending Protocol",
    symbol: "LEND",
    mintAddress: "4uQeVj5tqViQh7yWWGStvkEG1Zmhx6uasJtWCJziofM",
    marketCap: 1500000,
    price: 0.015,
    launchDate: "2023-10-20",
    hasLiquidity: true,
    verified: true,
    trending: false,
    logoUrl: "/vinyl-record.png",
  },
  {
    id: "9",
    name: "Decentralized Exchange",
    symbol: "DEX",
    mintAddress: "8FRFC6MoGGkMFQwngccyu69VnYbzykGeez7ignHVAFSN",
    marketCap: 3200000,
    price: 0.032,
    launchDate: "2023-09-15",
    hasLiquidity: true,
    verified: true,
    trending: true,
    logoUrl: "/dx-graffiti.png",
  },
  {
    id: "10",
    name: "Insurance Protocol",
    symbol: "INS",
    mintAddress: "5CK6Qiwm9qNvLmJKdRuYFNGv4xRVzMJXv5iZJJWXU3nT",
    marketCap: 750000,
    price: 0.0075,
    launchDate: "2024-03-01",
    hasLiquidity: false,
    verified: false,
    trending: false,
    logoUrl: "/intellectual-property-concept.png",
  },
  {
    id: "11",
    name: "Prediction Market",
    symbol: "PRED",
    mintAddress: "7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2",
    marketCap: null,
    price: null,
    launchDate: "2024-03-10",
    hasLiquidity: false,
    verified: false,
    trending: false,
    logoUrl: "/project-management-overview.png",
  },
  {
    id: "12",
    name: "Synthetic Assets",
    symbol: "SYNTH",
    mintAddress: "3i1UAi5VbSEYP8qDW6Mh2Gg2iSM8eBXFUr9hEiVYYHHN",
    marketCap: null,
    price: null,
    launchDate: "2024-03-15",
    hasLiquidity: false,
    verified: false,
    trending: false,
    logoUrl: "/abstract-geometric-sa.png",
  },
]
